server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_CONTAINER_NAME:mysql-test1}:3306/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
#    url: jdbc:mysql://139.196.152.44:33061/test?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: mypwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

